version: '3.8'

services:

  database:
    container_name: cadastro_db
    image: mysql
    environment:
      MYSQL_DATABASE: dbhospital
      MYSQL_USER: api_aplicacao
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    restart: always

  api:
    container_name: cadastro_api
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/home/api
      - /home/api/node_modules

